### ISSUE TITLE
ObjectId function not included

### ISSUE THREAD

**Issue by dieguito151** [nswbmw/koa-mongo#21]
I've been playing around with koa (v1) and koa-mongo (v0.6.0) for a few hours and I tried to implement an endpoint to retrieve a document with a specific _id; however, I can't seem to find any documentation on `mongo.ObjectId` and if it's included in koa-mongo. Since it seems it isn't included, I've added it to the module myself by adding it to `this.mongo` - although I'm not sure if I could achieve it in a different way. What's the correct approach for this?

If this is useful for someone else, I can create a pull request for this.

Thanks!

**Comment by nswbmw** [comment]
pr welcome :)

**Comment by dieguito151** [comment]
Reviewed your commit, and it is still missing for 0.x.

**Comment by nswbmw** [comment]
@dieguito151 https://github.com/nswbmw/koa-mongo/commit/31b2f7685bb61cdb736e18ed11cbc91accd69b48

**Comment by dieguito151** [comment]
@nswbmw awesome! thanks!
