### ISSUE TITLE
anyway to avoid having to specify the db in query query?

### ISSUE THREAD

**Issue by chovy** [nswbmw/koa-mongo#34]
I see I can specify the db when I connect, but all the examples show `ctx.db('test').collection()`.

Is there a way to avoid haivng to harcdoe the db in every query?

**Comment by nswbmw** [comment]
add `ctx.db` & bump v1.6.0.

```
ctx.db === ctx.mongo.db(dbName)
```

**Comment by chovy** [comment]
i'm not following. am i doing something wrong? why did you close the issue.

**Comment by nswbmw** [comment]
@chovy Sorry, i thought v1.6.0 resolve your problem..

**Comment by nswbmw** [comment]
ping @chovy

**Comment by chovy** [comment]
so i just use `ctx.db` if I specify the db when I connect?

**Comment by nswbmw** [comment]
yes
