### ISSUE TITLE
Filtering in find don't seems to work

### ISSUE THREAD

**Issue by Nerothos** [nswbmw/koa-mongo#35]
Hi, thanks for your work on this middleware.

I'm using this :
`await ctx.db.collection("characters").find({}, {name:1}).limit(1).toArray();`

Because I want to retrieve the field "name" of a document in the characters collection but it's returning every fields.
When I'm using the equivalent (ie: `db.characters.find({}, {name:1}).limit(1).toArray();`) in the mongo console the filtering is done.

Did I miss something or is this a bug?

**Comment by nswbmw** [comment]
mongo shell is different with Node.js `mongodb` client. Please use `projection` options, see http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#find

**Comment by Nerothos** [comment]
I don't understand, projection is what I am using with the `{name:1}` part.
